# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{reflex}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom-Eric Gerritsen"]
  s.date = %q{2010-02-15}
  s.description = %q{Reflex is a gem that allows you to connect your application to the React Social API}
  s.email = %q{tomeric@i76.nl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/reflex.rb",
     "lib/reflex/authlogic/acts_as_authentic.rb",
     "lib/reflex/authlogic/callback_filter.rb",
     "lib/reflex/authlogic/session.rb",
     "lib/reflex/base.rb",
     "lib/reflex/configuration.rb",
     "lib/reflex/oauth_server.rb",
     "lib/reflex/system.rb",
     "rails/init.rb",
     "spec/fakeweb/OAuthServer.getProviders",
     "spec/fakeweb/OAuthServer.tokenAccess",
     "spec/fakeweb/OAuthServer.tokenRequest",
     "spec/fakeweb/System.listMethods",
     "spec/fakeweb/System.methodDescription",
     "spec/fakeweb/System.methodSignature",
     "spec/reflex/configuration_spec.rb",
     "spec/reflex/oauth_server_spec.rb",
     "spec/reflex/system_spec.rb",
     "spec/reflex_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/i76/reflex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Reflex connects your app to the React Social API}
  s.test_files = [
    "spec/reflex/configuration_spec.rb",
     "spec/reflex/oauth_server_spec.rb",
     "spec/reflex/system_spec.rb",
     "spec/reflex_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<mime-types>, [">= 1.16"])
    else
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
  end
end

