# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{reflex}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom-Eric Gerritsen"]
  s.date = %q{2010-02-21}
  s.description = %q{Reflex is a gem that allows you to connect your application to the React Social API}
  s.email = %q{tomeric@i76.nl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cucumber.yml",
     "features/connect_to_provider.feature",
     "features/social_authentication.feature",
     "features/step_definitions/reflex_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/env.rb",
     "features/support/mocha.rb",
     "features/support/mock_controller.rb",
     "features/support/mock_controller/oauth_authorize.html.erb",
     "features/support/paths.rb",
     "features/support/rails_root/.gitignore",
     "features/support/rails_root/Rakefile",
     "features/support/rails_root/app/controllers/application_controller.rb",
     "features/support/rails_root/app/controllers/user_sessions_controller.rb",
     "features/support/rails_root/app/controllers/users_controller.rb",
     "features/support/rails_root/app/helpers/application_helper.rb",
     "features/support/rails_root/app/helpers/user_sessions_helper.rb",
     "features/support/rails_root/app/helpers/users_helper.rb",
     "features/support/rails_root/app/models/user.rb",
     "features/support/rails_root/app/models/user_session.rb",
     "features/support/rails_root/app/views/layouts/application.html.erb",
     "features/support/rails_root/app/views/user_sessions/new.html.erb",
     "features/support/rails_root/app/views/users/_form.html.erb",
     "features/support/rails_root/app/views/users/_user.html.erb",
     "features/support/rails_root/app/views/users/edit.html.erb",
     "features/support/rails_root/app/views/users/index.html.erb",
     "features/support/rails_root/app/views/users/new.html.erb",
     "features/support/rails_root/app/views/users/show.html.erb",
     "features/support/rails_root/config/boot.rb",
     "features/support/rails_root/config/database.yml",
     "features/support/rails_root/config/environment.rb",
     "features/support/rails_root/config/environments/development.rb",
     "features/support/rails_root/config/environments/test.rb",
     "features/support/rails_root/config/initializers/backtrace_silencers.rb",
     "features/support/rails_root/config/initializers/inflections.rb",
     "features/support/rails_root/config/initializers/mime_types.rb",
     "features/support/rails_root/config/initializers/new_rails_defaults.rb",
     "features/support/rails_root/config/initializers/session_store.rb",
     "features/support/rails_root/config/routes.rb",
     "features/support/rails_root/db/migrate/001_create_users.rb",
     "features/support/rails_root/db/migrate/002_create_reflex_connections.rb",
     "features/support/rails_root/db/schema.rb",
     "features/support/rails_root/vendor/plugins/reflex/rails/init.rb",
     "features/traditional_registration_and_authentication.feature",
     "init.rb",
     "lib/reflex.rb",
     "lib/reflex/authlogic/acts_as_authentic.rb",
     "lib/reflex/authlogic/callback_filter.rb",
     "lib/reflex/authlogic/connection.rb",
     "lib/reflex/authlogic/session.rb",
     "lib/reflex/base.rb",
     "lib/reflex/configuration.rb",
     "lib/reflex/oauth_server.rb",
     "lib/reflex/system.rb",
     "rails/init.rb",
     "rails_generators/reflex_connection_migration/reflex_connection_migration_generator.rb",
     "rails_generators/reflex_connection_migration/templates/create_reflex_connections.rb",
     "reflex.gemspec",
     "spec/fakeweb/OAuthServer.getProviders",
     "spec/fakeweb/OAuthServer.sessionGetProfile",
     "spec/fakeweb/OAuthServer.tokenAccess",
     "spec/fakeweb/OAuthServer.tokenRequest",
     "spec/fakeweb/OAuthServer.tokenSetUserId",
     "spec/fakeweb/OAuthServer.userGetProfile",
     "spec/fakeweb/OAuthServer.userGetProviders",
     "spec/fakeweb/OAuthServer.userRemoveProvider",
     "spec/fakeweb/System.listMethods",
     "spec/fakeweb/System.methodDescription",
     "spec/fakeweb/System.methodSignature",
     "spec/reflex/authlogic/connection_spec.rb",
     "spec/reflex/base_spec.rb",
     "spec/reflex/configuration_spec.rb",
     "spec/reflex/oauth_server_spec.rb",
     "spec/reflex/system_spec.rb",
     "spec/reflex_spec.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/i76/reflex}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Reflex connects your app to the React Social API}
  s.test_files = [
    "spec/reflex/authlogic/connection_spec.rb",
     "spec/reflex/base_spec.rb",
     "spec/reflex/configuration_spec.rb",
     "spec/reflex/oauth_server_spec.rb",
     "spec/reflex/system_spec.rb",
     "spec/reflex_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<mime-types>, [">= 1.16"])
    else
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
  end
end

